"""Build a cleaned zone raster from the reference map -> src/world/zonemap.js
zones: 1 sea, 2 sand/plaza, 3 field (grass loop), 4 forest/cliff, 5 town"""
import sys, base64
import numpy as np
from PIL import Image
from scipy import ndimage

SRC = sys.argv[1]
im = Image.open(SRC).convert('RGB')
a = np.array(im).astype(int); r, g, b = a[..., 0], a[..., 1], a[..., 2]
H, W = r.shape
bright = (r + g + b) / 3
SEA, SAND, FIELD, FOREST, TOWN = 1, 2, 3, 4, 5
z = np.zeros((H, W), np.uint8)
sea = (b > 170) & (b > r + 40)
cyan = (b > 160) & (g > 170) & (r > 120) & (np.abs(g - b) < 50) & ~(b > r + 70)
roof = (r > 170) & (g < 150) & (b < 150) & (r - g > 60)
sand = (r > 210) & (g > 160) & (b > 90) & (b < 200) & ~sea
field = (r > 165) & (g > 150) & (b < 115)
dark = bright < 150
z[dark] = FOREST; z[field] = FIELD; z[sand] = SAND; z[sea | cyan] = SEA
yy, xx = np.mgrid[0:H, 0:W]
from matplotlib.path import Path as MPath
TOWN_POLY = [(55,122),(100,118),(150,117),(195,120),(215,128),(225,145),(222,165),(205,175),(180,183),(140,183),(118,191),(85,196),(66,190),(56,170),(52,145)]
town_mask = MPath(TOWN_POLY).contains_points(np.stack([xx.ravel(), yy.ravel()], 1)).reshape(H, W)
# map border frame -> forest (outer cliffs)
z[:6, :] = FOREST; z[-6:, :] = SEA; z[:, :6] = FOREST; z[:, -6:] = FOREST
z[yy > 300] = np.where(z[yy > 300] == FOREST, SEA, z[yy > 300])  # bottom torn edge is sea

# --- corrections before cleanup
# the lighter band inside the northern field is the dirt path -> field
z[(yy < 172) & (z == SAND)] = FIELD
# --- the harbour half is authored explicitly (sea, plaza, island, cliffs)
def poly(pts):
    return MPath(pts).contains_points(np.stack([xx.ravel(), yy.ravel()], 1)).reshape(H, W)
south = yy >= 160
z[south & (z != FIELD)] = SEA
z[(yy >= 160) & (xx < 50) & (yy < 238)] = FOREST          # west cliffs
z[(yy >= 150) & (xx > 292) & (yy < 300)] = FOREST          # east cliffs
z[(yy >= 150) & (xx > 280) & (yy < 175)] = FOREST
PLAZA = [(56,168),(62,200),(80,214),(100,222),(120,232),(150,236),(180,229),(205,212),(216,200),(236,188),(260,181),(276,170),(274,158),(230,158),(56,158)]
z[poly(PLAZA)] = SAND
dI = np.hypot(xx - 252.5, yy - 260)
z[dI < 44] = SAND
z[np.hypot(xx - 236, yy - 302) < 11] = SAND
z[poly([(228,292),(244,292),(246,306),(226,306)])] = SAND

def cleanup(z, min_size):
    out = z.copy()
    for cls in [SEA, SAND, FIELD, FOREST, TOWN]:
        lab, n = ndimage.label(out == cls)
        sizes = ndimage.sum(np.ones_like(lab), lab, range(1, n + 1))
        small = np.isin(lab, np.nonzero(sizes < min_size)[0] + 1)
        out[small] = 0
    # fill holes (0) with the most common neighbour class, iteratively
    for _ in range(40):
        holes = out == 0
        if not holes.any(): break
        best = np.zeros_like(out); bestc = np.zeros(out.shape, int)
        for cls in [SEA, SAND, FIELD, FOREST, TOWN]:
            cnt = ndimage.uniform_filter((out == cls).astype(float), 5)
            m = cnt > bestc
            best[m] = cls; bestc = np.where(m, cnt, bestc)
        out[holes & (bestc > 0)] = best[holes & (bestc > 0)]
    return out

z = cleanup(z, 60)
z[town_mask] = TOWN
# smooth jaggies with a mode filter
for _ in range(2):
    counts = np.stack([ndimage.uniform_filter((z == c).astype(float), 3) for c in range(6)])
    z = counts.argmax(0).astype(np.uint8)
z = cleanup(z, 60)
z[town_mask] = TOWN

pal = np.array([[255, 0, 255], [40, 110, 220], [240, 200, 150], [230, 220, 90], [60, 80, 40], [170, 170, 200]], np.uint8)
Image.fromarray(pal[z]).resize((W * 2, H * 2), Image.NEAREST).save(sys.argv[2])
# RLE encode
flat = z.reshape(-1)
runs = []
i = 0
while i < len(flat):
    j = i
    while j < len(flat) and flat[j] == flat[i] and j - i < 255: j += 1
    runs += [flat[i], j - i]; i = j
enc = base64.b64encode(bytes(runs)).decode()
with open(sys.argv[3], 'w') as f:
    f.write('// Generated by tools/make_zones.py from the Roumen reference map. Do not edit by hand.\n')
    f.write('// zones: 1 sea, 2 sand/plaza, 3 field, 4 forest/cliff, 5 town\n')
    f.write(f'export const ZONE_W = {W};\nexport const ZONE_H = {H};\n')
    f.write(f"const RLE = '{enc}';\n")
    f.write('''export const ZONES = (() => {
  const bin = atob(RLE);
  const out = new Uint8Array(ZONE_W * ZONE_H);
  let o = 0;
  for (let i = 0; i < bin.length; i += 2) { const v = bin.charCodeAt(i), n = bin.charCodeAt(i + 1); out.fill(v, o, o + n); o += n; }
  return out;
})();
''')
print('runs', len(runs) // 2, 'bytes', len(enc))
